//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertecControlBodega.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public long id_mov { get; set; }
        public int id_producto { get; set; }
        public System.DateTime fecha_mov { get; set; }
        public string ot { get; set; }
        public double cantidad { get; set; }
        public string obs_mov { get; set; }
    
        public virtual Ingreso_Prod Ingreso_Prod { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Salida_Prod Salida_Prod { get; set; }
    }
}
