//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertecControlBodega.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida_Prod
    {
        public long id_mov { get; set; }
        public int id_trabajador { get; set; }
        public int folio { get; set; }
    
        public virtual Movimiento Movimiento { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
